### ISSUE TITLE
Regex for dependabot is too permissive for generate-yaml

### ISSUE THREAD

**Issue by paologallinaharbur** [newrelic/release-toolkit#108]
[This](https://github.com/newrelic/newrelic-prometheus-configurator/pull/125/files) commit is interpreted as a dependabot one.

```
notes: ""
changes: []
dependencies:
    - name: configurator
      meta:
        pr: "125"
        commit: 25153bf1101695b03f8a572b395f0070d39387fd
```
