### ISSUE TITLE
Add a link-changelog command/action

### ISSUE THREAD

**Issue by nadiamoe** [newrelic/release-toolkit#53]
For packages that mostly wrap other packages, e.g. the [nri-bundle](https://github.com/newrelic/helm-charts/tree/master/charts/nri-bundle) helm chart, the ability to link to a dependency changelog would be very desirable. For example:

---

### Dependencies

- Upgraded newrelic-infrastructure chart to v3.2.1 ([See changes](#))

---

This could be tricky and might need some heuristics to work, specially if we don't have the full dependency name. In the worst case scenario, we might need to ask users for a dictionary from dependency names to changelog URLs, e.g. something like
```yaml
dependencyChangelogs:
  newrelic-infrastructure: "https://github.com/newrelic/nri-kubernetes/releases/tag/newrelic-infrastructure-%s"
  infrastructure-agent: "https://github.com/newrelic/infrastructure-agent/releases/tag/%s"
```

If we have full dependency names, e.g. `github.com/newrelic/nri-kubernetes` instead of `nri-kubernetes`, we might not need this.
