### ISSUE TITLE
`link-changelog` is removing commit metadata

### ISSUE THREAD

**Issue by gsanchezgavier** [newrelic/release-toolkit#92]
to reproduce:

```
rt generate --excluded-dirs "charts,.github" --tag-prefix "v"
```

Generated changelog.yaml
```yaml
notes: ""
changes: []
dependencies:
    - name: dependencies
      meta:
        pr: "105"
        commit: 8996fddbe59275f9103ceac77dfcd3ed391a6f92
```

then execute `rt link-changelog`
```yaml
notes: ""
changes: []
dependencies:
    - name: dependencies

```

NOTE: this commit is not from a bot. but looks like is computed as a dependabot since if I do 

```
rt generate --excluded-dirs "charts,.github" --tag-prefix "v" --dependabot=false
```
the commit is not listed. 

This is the actual [commit](https://github.com/newrelic/newrelic-prometheus-configurator/commits/main). And I'm generating the release from this [commit](https://github.com/newrelic/newrelic-prometheus-configurator/commit/31af1f7e11cc7613784bc75f7b11ce1821eb034d)
